config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'home#index'

  namespace :admin do
    root to: 'home#index'
    devise_for :users, controllers: { registrations: 'admin/registrations', sessions: 'admin/sessions' }
    resources :categories
    resources :courses
  end

  mount ApiRoot => '/'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :courses
  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/course.rb
class Course < ApplicationRecord
  CURRENCIES = Rails.application.config_for(:settings)['support_currencies']
  belongs_to :category
  has_many :orders
  has_many :purchased_records, -> { purchased }, class_name: :Order

  scope :filter_by_category , lambda { |category| 
    includes(:category).where( categories: { name: category } )
  }

  enum status: { discontinued: 0, released: 1 }

  validates :title, :slug, presence: true, uniqueness: { case_sensitive: false }
  validates :period, inclusion: { in: (1..30) }
  validates :price_currency, inclusion: { in: CURRENCIES }

  monetize :price_cents
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :course
  before_create :set_amount

  validate :check_course_status
  validate :check_duplicate_purchase, on: :create

  scope :not_expired, -> { paid.where('expired_at > ?', DateTime.now) }
  scope :purchased, -> { where(state: %i[paid expired]) }

  monetize :amount_cents
  
  include AASM

  aasm column: :state do
    state :pending, initial: true
    state :paid, :expired, :revoked

    event :pay, after_commit: %i[set_expired_time set_paid_time] do
      transitions from: :pending, to: :paid
    end

    event :expire do
      transitions from: :paid, to: :expired
    end

    event :revoked do
      transitions from: :pending, to: :revoked
    end
  end

  private

  def set_amount
    return unless course.present?
    
    self.amount = course.price
    self.amount_currency = course.price_currency
  end

  def set_expired_time
    update(expired_at: course.period.days.after)
  end

  def set_paid_time
    update(paid_at: DateTime.now) 
  end

  def check_course_status
    return if course&.released?

    errors.add(:course, :is_discontinued)
  end

  def check_duplicate_purchase
    return unless user.orders.not_expired.pluck(:course_id).include?(course.id)

    errors.add(:course, :is_duplicated_purchase)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_secure_token :auth_token
  has_many :orders
  has_many :purchased_records, -> { purchased }, class_name: :Order
  has_many :purchased_courses, -> { distinct }, through: :purchased_records, source: :course
  has_many :available_records, -> { not_expired }, class_name: :Order
  has_many :available_courses, -> { distinct }, through: :available_records, source: :course
  
  enum role: { member: 0, admin: 1 }

  def renew_token!
    regenerate_auth_token
    auth_token
  end
end

app/controllers/admin/base_controller.rb
# frozen_string_literal: true

class Admin::BaseController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin_user!
end

app/controllers/admin/categories_controller.rb
# frozen_string_literal: true

class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: %i[edit update destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, notice: t('flash.create.notice')
    else
      flash[:alert] = t('flash.create.alert')
      render :new
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to admin_categories_path, notice: t('flash.update.notice')
    else
      flash[:alert] = t('flash.update.alert')
      render :edit
    end
  end

  def destroy
    redirect_to admin_categories_path, notice: t('flash.destroy.notice') if @category.destroy
  end

  private
  
  def set_category
    @category = Category.find params[:id]
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/admin/courses_controller.rb
# frozen_string_literal: true

class Admin::CoursesController < Admin::BaseController
  before_action :set_course, only: %i[edit update show destroy]
  before_action :set_url, except: :index

  def index
    @courses = Course.includes(:category)
  end

  def show
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to admin_courses_path, notice: t('flash.create.notice')
    else
      flash[:alert] = t('flash.create.alert')
      render :new
    end
  end

  def edit; end

  def update
    if @course.update(course_params)
      redirect_to admin_courses_path, notice: t('flash.update.notice')
    else
      flash[:alert] = t('flash.update.alert')
      render :edit
    end
  end

  def destroy
    redirect_to admin_courses_path, notice: t('flash.destroy.notice') if @course.destroy
  end

  private
  
  def set_course
    @course = Course.find params[:id]
  end

  def set_url
    @base_url = request.base_url.to_s
  end

  def course_params
    params.require(:course).permit(:title, :status, :period, :slug, :category_id,
                                   :description, :price, :price_currency)
  end
end

app/controllers/admin/home_controller.rb
# frozen_string_literal: true

class Admin::HomeController < Admin::BaseController
  def index; end
end

app/controllers/admin/registrations_controller.rb
# frozen_string_literal: true

class Admin::RegistrationsController < Devise::RegistrationsController
  layout 'admin'
  before_action :configure_sign_up_params, only: [:create]

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    admin_root_path
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  layout 'admin'
  def after_sign_in_path_for(resource_or_scope)
    admin_root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    new_admin_user_session_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/_form.html.erb
<%= form_with model: [:admin, category], local: true do |f| %>
  <% if category.errors.any? %>
    <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group row mb-3">
    <%= f.label :name, class: 'form-label' %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row mb-3">
    <div class="col-sm-10">
      <%= f.submit t('view.submit'), class: 'btn btn-dark btn-sm' %>
      <%= link_to t('view.return'), admin_categories_path, class: 'btn btn-secondary btn-sm' %> 
    </div>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<div class="container col-4 mt-5">
  <h3 class='mb-3'><%= t('view.edit') %><%= Category.model_name.human %></h3>
  <%= render "form", category: @category %>
</div>

app/views/admin/categories/index.html.erb
<div class="container col-4 mt-5">
  <div class="d-flex justify-content-between mb-3">
    <h3><%= Category.model_name.human %></h3>
    <%= link_to t('view.new'), new_admin_category_path, class: 'btn btn-dark' %>
  </div>

  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col" class='col-9'><%= Category.human_attribute_name(:name) %></th>
        <th scope="col"><%= t('view.action') %>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.name.humanize %></td>
          <td>
            <%= link_to t('view.edit'), edit_admin_category_path(category), class: "btn btn-dark btn-sm" %>
            <%= link_to t('view.destroy'), admin_category_path(category), class: "btn btn-danger btn-sm", method: :delete, data: { confirm: t('view.destroy_confirm') } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/categories/new.html.erb
<div class="container col-4 mt-5">
  <h3 class='mb-3'><%= t('view.new') %><%= Category.model_name.human %></h3>
  <%= render "form", category: @category %>
</div>

app/views/admin/courses/_form.html.erb
<%= form_with model: [:admin, course], local: true do |f| %>
  <% if course.errors.any? %>
    <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group row mb-3">
    <%= f.label :title, class: 'form-label' %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row mb-3">
    <%= f.label :category_id, class: 'form-label' %>
    <div class="col-sm-10">
      <%= f.select :category_id, options_for_select(Category.all.map { |category| [ category.name, category.id ] }), {}, class: 'form-select' %>
    </div>
  </div>

  <div class="form-group row mb-3">
    <%= f.label :description, class: 'form-label' %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row mb-3">
    <%= f.label :status, class: 'form-label' %>
    <div class="col-sm-10">
      <%= f.select :status, options_for_select(Course.statuses.keys.map{ |k| [k, k] }), {}, class: 'form-select' %>
    </div>
  </div>

  <div class="form-group row mb-3">
    <%= f.label :slug, class: 'form-label' %>
    <div class="col-sm-10">
      <div class="input-group">
        <span class="input-group-text"><%= @base_url %>/</span>
        <%= f.text_field :slug, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="form-group row mb-3">
    <%= f.label :price, class: 'form-label' %>
    <div class="col-sm-6">
      <%= f.number_field :price, class: 'form-control', required: true %>
    </div>
    <div class="col-sm-4">
      <%= f.select :price_currency, options_for_select(Course::CURRENCIES.map{ |currency| [currency, currency] }), {}, class: 'form-control'%>
    </div>
  </div>

  <div class="form-group row mb-3">
    <%= f.label :period, class: 'form-label' %>
    <div class="col-sm-10">
      <%= f.number_field :period, in: 1..30, step: 1, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row mb-3">
    <div class="col-sm-10">
      <%= f.submit t('view.submit'), class: 'btn btn-dark btn-sm' %>
      <%= link_to t('view.return'), admin_courses_path, class: 'btn btn-secondary btn-sm' %> 
    </div>
  </div>
<% end %>

app/views/admin/courses/edit.html.erb
<div class="container col-4 mt-5">
  <h3 class='mb-3'><%= t('view.edit') %><%= Course.model_name.human %></h3>
  <%= render "form", course: @course %>
</div>

app/views/admin/courses/index.html.erb
<div class="container col-9 mt-5">
  <div class="d-flex justify-content-between mb-3">
    <h3><%= Course.model_name.human %></h3>
    <%= link_to t('view.new'), new_admin_course_path, class: 'btn btn-dark' %>
  </div>

  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col"><%= Course.human_attribute_name(:title) %></th>
        <th scope="col"><%= Course.human_attribute_name(:category) %></th>
        <th scope="col"><%= Course.human_attribute_name(:status) %></th>
        <th scope="col"><%= Course.human_attribute_name(:price) %></th>
        <th scope="col"><%= Course.human_attribute_name(:price_currency) %></th>
        <th scope="col" class="col-2"><%= t('view.action') %>
      </tr>
    </thead>
    <tbody>
      <% @courses.each do |course| %>
        <tr>
          <td><%= course.title %></td>
          <td><%= course.category.name %></td>
          <td><%= Course.human_attribute_name("statuses.#{course.status}") %></td>
          <td><%= course.price %></td>
          <td><%= course.price_currency %></td>
          <td>
            <%= link_to t('view.edit'), edit_admin_course_path(course), class: "btn btn-dark btn-sm" %>
            <%= link_to t('view.destroy'), admin_course_path(course), class: "btn btn-danger btn-sm", method: :delete, data: { confirm: t('view.destroy_confirm') } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/courses/new.html.erb
<div class="container col-4 mt-5">
  <h3 class='mb-3'><%= t('view.new') %><%= Course.model_name.human %></h3>
  <%= render "form", course: @course %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CourseBuy Management</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/admin_navbar' %>
    <%= render 'shared/flash' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CourseBuy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p><%= notice %></p>
    <p><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_admin_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">CourseBuy Management</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to t('nav.courses_management'), admin_courses_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to t('nav.categories_management'), admin_categories_path, class: 'nav-link' %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto">
        <% if admin_user_signed_in? %>
          <span class="navbar-text"><%= current_admin_user.email %></span> |
          <li><%= link_to 'Logout', destroy_admin_user_session_path, method: :delete, class: 'nav-link' %></li>
        <% else %>
          <li><%= link_to 'SignIn', new_admin_user_session_path, class: 'nav-link' %></li>
          <li><%= link_to 'SignUp', new_admin_user_registration_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-warning" role="alert">
    <%= flash[:alert] %> 
  </div>
<% end %>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">CourseBuy</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <span class="navbar-text"><%= current_user.email %></span> |
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
        <% else %>
          <li><%= link_to 'SignIn', new_user_session_path, class: 'nav-link' %></li>
          <li><%= link_to 'SignUp', new_user_registration_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>